<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AssemblyName>tensile-diag</AssemblyName>

    <Optimize>true</Optimize>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <TieredPGO>false</TieredPGO>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Tensile/Tensile.csproj" />
  </ItemGroup>

</Project>
